[package]
name = "ofdb-cli"
version = "0.0.0"
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2018"

[[bin]]
name = "ofdb"
path = "src/main.rs"

[dependencies]
anyhow = "1"
chrono = "*"
csv = "1"
pretty_env_logger = "*"
log = "0.4"
ofdb-boundary = { version = "0.10", features = [ "extra-derive" ] }
ofdb-core = "*"
ofdb-entities = { version = "0.10", features = [ "rusturl" ] }
ofdb-gateways = "*"
uuid = "0.8"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
structopt = "0.3"
thiserror = "1"

[dependencies.reqwest]
version = "0.11"
default-features = false
features = ["rustls-tls", "blocking", "json", "cookies"]

[dev-dependencies]
env_logger = "*"
ofdb-entities = "*"
url = { version = "2.2", features = [ "serde" ] }
uuid = { version = "0.8", features = [ "serde" ] }

[patch.crates-io]
ofdb-core     = { git = "https://github.com/kartevonmorgen/openfairdb" }
ofdb-boundary = { git = "https://github.com/kartevonmorgen/openfairdb" }
ofdb-entities = { git = "https://github.com/kartevonmorgen/openfairdb" }
ofdb-gateways = { git = "https://github.com/kartevonmorgen/openfairdb" }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
